# Generated by Django 5.1.4 on 2026-09-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_url_project_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], default='software', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g 'Django, DRF, PostgreSQL'", max_length=200),
        ),
    ]
